//TODO: do not use until confirmation

const getCommonProperties = (
  $formStore: any,
  formattedCandidateDate: any,
  exteriorCondition: string[],
  interiorCondition: string[],
  otherItems: string[],
): Record<string, any> => ({
  id: response_id,
  ctn_wpc_f7_counter: ctn_wpc_f7_counter,
  Meka: Meka,
  CarName: CarName,
  caryear: caryear,
  carversion: carversion,
  carmet: carmet,
  color: color,
  month: month,
  status: status,
  auto: auto,
  history: history,
  "your-name": $formStore.yourname,
  zipcode: $formStore.zipcode,
  address: $formStore.pref + $formStore.address,
  address2: $formStore.address2,
  manson: $formStore.manson,
  "your-email": $formStore.youremail,
  tel: $formStore.tel,
  form_pref: $formStore.pref,
  form_address: $formStore.address,
  "cf7msm-no-ss": "",
  cf7msm_options: '{"last_step":1,"send_email":1}',
  xilanh: engineCapacity,
  zansai: loan,
  shaken: inspectionDate,
  shane: fuel,
  shapa: getTranslatedBoolean(exteriorCondition.includes("傷")),
  shahe: getTranslatedBoolean(exteriorCondition.includes("へこみ")),
  shage: getTranslatedBoolean(exteriorCondition.includes("塗装はげ")),
  shapi: getTranslatedBoolean(exteriorCondition.includes("さび")),
  nairua: getTranslatedBoolean(interiorCondition.includes("汚れ/シミ")),
  naishito: getTranslatedBoolean(interiorCondition.includes("シート破れ")),
  naitabaco: getTranslatedBoolean(interiorCondition.includes("喫煙")),
  sohinnabi: navigation,
  sohinden: electricSlide,
  sohinshito: getTranslatedBoolean(otherItems.includes("革シート")),
  sohinmonitor: getTranslatedBoolean(otherItems.includes("バックモニター")),
  sohinsan: getTranslatedBoolean(otherItems.includes("サンルーフ")),
  "date-881": formattedCandidateDate,
});

const reqMail: Record<string, any> = getCommonProperties(
  $formStore,
  formattedCandidateDate,
  exteriorCondition,
  interiorCondition,
  otherItems,
);

const reqDetail: Record<string, any> = {
  ...getCommonProperties(
    $formStore,
    formattedCandidateDate,
    exteriorCondition,
    interiorCondition,
    otherItems,
  ),
  sohintaiya: getSohintaiyaBoolean(otherItems.includes("アルミホイール")),
};
